# After curl'ing and applying
# https://raw.githubusercontent.com/metallb/metallb/main/manifests/metallb.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: metal-lb-ip-space
      protocol: layer2
      addresses:
      - 172.16.1.240-172.16.1.250
