kind: Service
apiVersion: v1
metadata:
  name: traefik2-service
spec:
  selector:
    k8s-app: traefik2-clusterip
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 8080
      name: admin
    - protocol: TCP
      port: 443
      name: secure
  type: ClusterIP
  externalIPs:
  - {{INTERNAL_HOST_IP}}

---
kind: Middleware
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: tls-redirect
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
kind: Secret
apiVersion: v1
metadata:
  name: api-secret
  namespace: default
data:
  auth: {{BASE64_ENCODED_HTPASSWD}}
  # replace above with `htpasswd -nb <user> <passwd> | base64`

---
kind: Middleware
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: api-auth
  namespace: default
spec:
  basicAuth:
    secret: api-secret
