kind: Service
apiVersion: v1
metadata:
  name: whoami
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
  selector:
    run: whoami-app

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      run: whoami-app
  template:
    metadata:
      labels:
        run: whoami-app
    spec:
      containers:
        - name: whoami-ctr
          image: containous/whoami
          ports:
            - name: web
              containerPort: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: simpleingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`k3sgcp.ackerson.de`) && PathPrefix(`/notls`)
    kind: Rule
    services:
    - name: whoami
      port: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: default
spec:
  entryPoints:
    - secure
  routes:
  - match: Host(`k3sgcp.ackerson.de`) && PathPrefix(`/tls`)
    kind: Rule
    services:
    - name: whoami
      port: 80
