apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: default
spec:
  ports:
    - name: plex
      protocol: TCP
      port: 32400
      targetPort: 32400

---
apiVersion: v1
kind: Endpoints
metadata:
  name: plex
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.178.59
    ports:
      - port: 32400
        name: plex

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: plex-ingress
  namespace: default
spec:
  entryPoints:
    - web
    - secure
  routes:
  - match: Host(`plex.ackerson.de`)
    middlewares:
    - name: tls-redirect
    - name: api-auth
    kind: Rule
    services:
    - name: plex
      port: 32400
